title: "StarRingLand Official Site"
description: "同人サークル StarRingLand の公式サイト"
theme: minima

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    inlinemathdelims: ['$', '$']
    displaymathdelims: ['$$', '$$']
